[package]
name = "rust_playground"
version = "0.1.0"
edition = "2024"

[dependencies]

# [[example]] must stay [[example]] is a Cargo-defined table name
# name should be lowercase letters/numbers with _ or -
# path should point to the .rs file
# cargo run --example random_password_cli
[[example]]
name = "random_password_cli"
path = "projects/random_password_cli.rs"
